### PR TITLE
feat(manifest): add `useWebmanifestExtension` option and improve docs

### PR DESCRIPTION
**Pull request by gangsthub**
According to [the spec [W3]](https://www.w3.org/TR/appmanifest/#using-a-link-element-to-link-to-a-manifest) (and [W3C](https://w3c.github.io/manifest/#using-a-link-element-to-link-to-a-manifest)):

> The official file extension for the manifest is `.webmanifest`.

- I added the option in the Manifest module but left the "json" as the default one for backward compatibility.

    Using `.webmanifest` is also recommended by [Webhint](https://webhint.io/docs/user-guide/hints/hint-manifest-file-extension/).

- I also ~added some tests (mocking the _hasha_ module)~ updated the snapshots.
- And edited the documentation to show the default options.

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
@gangsthub it would be interesting to warn the user if the extension type is different from `.webmanifest`

**Comment by gangsthub** [comment]
I reverted mocking the package `hasha` as it was returning the mocked value in built files:

https://github.com/nuxt-community/pwa-module/blob/13d38926a14d7e42100edec7c90e6bbb2367ca71/test/__snapshots__/pwa.test.js.snap#L20

But not in `generate`d files (13d3892): https://github.com/nuxt-community/pwa-module/blob/13d38926a14d7e42100edec7c90e6bbb2367ca71/test/__snapshots__/pwa.test.js.snap#L46

And I didn't know why or how to fix it 🤔

**Comment by pi0** [comment]
Hi @gangsthub and thanks for this PR ❤️  I'm so sad to say I think it's not a good idea to recommend using non-JSON extension by users. I'm still up with adding a simple flag (Like `workbox.useWebmanifest: true`) option to change extension to spec recommended one. Please reopen a new PR if you wish to. And still open to discussions here, a new issue or discord.

PS: I've tried to explain it as much as i can and add relative issues in a wiki page: https://github.com/nuxt-community/pwa-module/wiki/.webmanifest

**Comment by ricardogobbosouza** [comment]
@pi0 or should this PR change?
Prompt user if manifest file extension is different from json.

**Comment by pi0** [comment]
@ricardogobbosouza I think so. Just adding a flag to change ext should be enough. There are enough reasons to not warn users, etc. And no reason to make it more complicated to allow any extension.

**Comment by gangsthub** [comment]
Noted. It's correct, it makes no sense to give freedom on choosing an extension different than `json` or `webmanifest`. I'll be:

- changing the option,
- deleting the warning and
- updating the rest.

**Comment by Heziode** [comment]
Any update ?

**Comment by pi0** [comment]
Thanks, @gangsthub. I've merged and also updated the wiki to include [webhint](https://webhint.io/docs/user-guide/hints/hint-manifest-file-extension/)

**Pull request merged**
