### PR TITLE
feat(workbox): offline analytics

### PR DESCRIPTION
**Pull request by manniL**
Related: #54 

Depends on: #60

### CODE REVIEW

**Comment by pi0** [comment]
Thanks, @manniL.

I think @MatteoGabriele has a better vision about this than me. As he is the creator of [vue-analytics](https://github.com/MatteoGabriele/vue-analytics) :)

**Comment by MatteoGabriele** [comment]
Hi @manniL 
it definitely sounds like a nice feature for a PWA, what is your problem? :)

**Comment by manniL** [comment]
Hey @MatteoGabriele!

Thank you :relaxed:

I was unsure about a few things, including how to handle `lodash templates` properly (but that's more a Nuxt thing) and how to test the behavior correctly. But I think I solved most of the problems I had by now :smiley:

**Comment by pi0** [comment]
@manniL So please tell me when it was ready to merge.

**Comment by manniL** [comment]
@pi0 Will do :ok_hand:

**Comment by manniL** [comment]
@pi0 As far as I figured it out, this feature can't be realized without updating `workbox-build`/`workbox-sw` to version three.

Related: #60

**Comment by husayt** [comment]
@manniL / @pi0 is anything stopping us from updating workbox-build/workbox-sw to version three?

**Comment by galvez** [comment]
@manniL @pi0 https://github.com/GoogleChrome/workbox/commit/f2e3165138ee59c9cd18e1a62f5118b0065dc1a5 :)

**Comment by manniL** [comment]
Awesome! thanks for the hint @galvez

**Comment by pi0** [comment]
Closing as PR is outdated :(

**Pull request closed without merging**
