### PR TITLE
Add author property

### PR DESCRIPTION
**Pull request by manniL**

### CODE REVIEW

**Comment by pi0** [comment]
Inside nuxt.config:

```js
meta: {
 author: false
}
```

**Comment by core01** [comment]
@pi0 my meta is array
```
 meta: [
      {
        charset: 'utf-8'
      },
      {
        name: 'viewport',
        content:
          'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
      },
      {
        hid: 'description',
        name: 'description',
        content: 'Citytorg.kz'
      },
      {
        name: 'theme-color',
        content: '#ffffff'
      },
      {
        name: 'msapplication-TileColor',
        content: '#00a300'
      },
    ],
```

**Comment by manniL** [comment]
@core01 Not `head.meta`.

It's about the top-level `meta` key.

Example: https://github.com/Developmint/developmint.de/blob/master/nuxt.config.js#L140
(That line would be `author: false` in your case).

**Comment by core01** [comment]
@manniL thank you, that makes sense!

**Pull request merged**
