### PR TITLE
fix(workbox): New configuration for specifying plugins when configuring a strategy

### LINKED ISSUE #336: RuntimeCaching.strategyOptions.cacheExpiration is deprecated in Workbox v3
Workbox has deprecated the use of `cacheExpiration` as a parameter of the strategies classes in `workbox-strategies` module. The constructor style Plugins are suggested. As described on [this page](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2#workbox-strategies_formerly_know_as_workbox-runtime-caching):
> The syntax for specifying plugins when configuring a strategy has changed. Each plugin needs to be explicitly listed in the `plugins` property of the strategy's configuration.

In our [`sw.js` template](https://github.com/nuxt-community/pwa-module/blob/eedf23fa3ab478f8a449817528d0270507babfc8/lib/workbox/templates/sw.js#L60), we are still using the old-style way to set up plugins using `JSON.stringify` to serialise the entire `strategyOptions` (not sure whether this is still working in v5). Also because of the use of `JSON.stringify`, incorporating the new way is not possible in the Nuxt config file.

Furthermore, [the TypeScript declaration](https://github.com/nuxt-community/pwa-module/blob/8723d076cb87ff9e583ba755f72f4d62360d6eb1/types/workbox.d.ts) also contains the old `cacheExpiration` field. 

[The documentation](https://github.com/nuxt-community/pwa-module/blob/88a94f856fe40353b973bd987850266561ab061f/docs/content/en/workbox.md#adding-custom-cache) also contains the old way to set up plugins for Workbox Strategies.

### PR DESCRIPTION
**Pull request by Yihao-G**
Fixes #336

### CODE REVIEW

**Comment by pi0** [comment]
Hi @Yihao-G thanks for efforts on PR i really appreciate it. However it is probably not best way to serialize/genenerate runtime code directly from `nuxt.config` and we are moving away from it. It is possible to use [workboxextensions](https://pwa.nuxtjs.org/workbox#workboxextensions) to inject custom code to generated `sw.js` or completely override template using using [swtemplate](https://pwa.nuxtjs.org/workbox/#swtemplate). Shall we directly use plugin and only support subset of json-serializable options?

**Comment by Yihao-G** [comment]
@pi0 Done. Let me know if there is anything else that can be improved :)

**Comment by Yihao-G** [comment]
Because of the change of the configuration structure, this is a breaking change ~~(well, I guess the current one does nothing anyway)~~. Should we stay with the original configuration structure? However, the plugin like `BackgroundSyncPlugin`, its constructor has two parameters.

**Comment by pi0** [comment]
Nice recent refactors @Yihao-G :+1: I have to locally test your changes before merge to also check breaking change possibility. Thanks again :heart:

**Comment by pi0** [comment]
Hi @Yihao-G I have refactored code to a runtime approach to reduce template complexity (1f1b23588b87f53ae58d958191ba1e1d5c4d207f), merging to [refactor/runtime-sw](https://github.com/nuxt-community/pwa-module/tree/refactor/runtime-sw) branch to apply this convention for rest of the template. Everything is currently working fine thanks for initiative :+1:

**Pull request merged**
