### PR TITLE
Add option to register third-party SW

### PR DESCRIPTION
**Pull request by Darkside73**
Use case: https://documentation.onesignal.com/docs/web-push-sdk-setup-https#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-

### CODE REVIEW

**Comment by pi0** [comment]
I was thinking of a way to provide custom templates. But this seems a nice workaround for now :)

**Comment by Darkside73** [comment]
Thanks) How I can add workbox package from github master branch?

**Comment by pi0** [comment]
No worries, I'll publish the new version in few minutes.

**Comment by pi0** [comment]
FIY: https://github.com/nuxt-community/pwa-module#-onesignal-module

**Pull request merged**
